version: "3.9"
services:
  ingestion:
    build: .
    volumes:
      - /var/lib/hypergraph/ingestion_docs:/app/ingestion_docs
    environment:
      - NEO4J_URI=${NEO4J_URI}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
    user: "1000:1000"  # Match hypergraph user ID
    networks:
      - skillsphere

networks:
  skillsphere:
    name: skillsphere
