[project]
name = "myjobagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "markitdown>=0.0.1a3",
    "owlready2>=0.47",
    "pandoc-plantuml-filter>=0.1.5",
    "pyyaml>=6.0.2",
]
