name: SkillSphere MCP Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'skill_sphere_mcp/**'
      - '.github/workflows/skill_sphere_mcp_tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'skill_sphere_mcp/**'
      - '.github/workflows/skill_sphere_mcp_tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.17]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd skill_sphere_mcp
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run tests
      run: |
        cd skill_sphere_mcp
        PYTHONPATH=. pytest tests/ -v --cov=src

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        directory: ./skill_sphere_mcp/coverage/
        fail_ci_if_error: true
