# docker-compose.yml
version: '3.8'

services:
  neo4j:
    image: neo4j:5.15.0
    container_name: neo4j
    env_file:
      - .env
    environment:
      # Overrides env_file for Neo4j auth
      NEO4J_AUTH: "${MCP_NEO4J_USER}/${MCP_NEO4J_PASSWORD}"
      NEO4J_dbms_security_allow_csv_import_from_file_urls: "true"
    ports:
      - "7474:7474"    # HTTP UI
      - "7687:7687"    # Bolt
    volumes:
      - neo4jdata:/data

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.85.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317"    # OTLP gRPC

  mcp-server:
    build: .
    container_name: mcp-server
    env_file:
      - .env
    volumes:
      - ./src:/app/src:ro
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
      - otel-collector

volumes:
  neo4jdata:

