# docker-compose.yml

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.85.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    depends_on:
      - tempo

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml:ro
      - ./tempo-data:/tmp/tempo
    ports:
      - "3200:3200"   # tempo
      - "4317:4317"   # otlp grpc
      - "4318:4318"   # otlp http

  mcp-server:
    build: .
    container_name: mcp-server
    env_file:
      - .env
    volumes:
      - ./src:/app/src:ro
    ports:
      - "8000:8000"
    depends_on:
      - otel-collector
      - tempo

volumes:
  tempo-data:
    driver: local

