name: Hypergraph Tests and Linting

on:
  push:
    branches: [ main ]
    paths:
      - 'hypergraph/**'
      - '.github/workflows/hypergraph.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'hypergraph/**'
      - '.github/workflows/hypergraph.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        check: [pylint, pytest, coverage]
        python-version: [3.10.17]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Cache uv packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-uv-

    - name: Cache virtual environment
      uses: actions/cache@v4
      with:
        path: .venv
        key: ${{ runner.os }}-venv-hypergraph-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-hypergraph-

    - name: Install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install --upgrade pip
        uv pip install -r requirements.txt
        uv pip install pytest pytest-cov pylint pytest-asyncio
        uv pip install -e hypergraph

    - name: Create pylint config
      run: |
        echo "[MASTER]
        disable=C0111,C0103,C0305,C0321,W0401,W0622,W0614
        max-line-length=120
        ignore=CVS
        persistent=yes
        load-plugins=pylint.extensions.docparams,pylint.extensions.docstyle,pylint.extensions.mccabe
        ignored-modules=uvicorn,fastapi
        " > .pylintrc

    - name: Run pylint
      if: matrix.check == 'pylint'
      run: |
        source .venv/bin/activate
        cd hypergraph
        pylint --rcfile=../.pylintrc --fail-under=9.0 $(git ls-files '*.py')

    - name: Run pytest
      if: matrix.check == 'pytest'
      run: |
        source .venv/bin/activate
        cd hypergraph
        pytest tests/ -v

    - name: Run coverage and generate badge
      if: matrix.check == 'coverage'
      run: |
        source .venv/bin/activate
        cd hypergraph
        pytest tests/ -v --cov=. --cov-report=xml
        coverage report -m

    - name: Generate coverage badge
      if: matrix.check == 'coverage'
      uses: tj-actions/coverage-badge-py@v2
      with:
        working-directory: ./hypergraph
        output: ./hypergraph/coverage.svg

    - name: Verify Changed files
      if: matrix.check == 'coverage'
      uses: tj-actions/verify-changed-files@v16
      id: verify-changed-files
      with:
        files: hypergraph/coverage.svg

    - name: Commit files
      if: matrix.check == 'coverage' && steps.verify-changed-files.outputs.files_changed == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add hypergraph/coverage.svg
        git commit -m "Updated hypergraph coverage badge"

    - name: Push changes
      if: matrix.check == 'coverage' && steps.verify-changed-files.outputs.files_changed == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.github_token }}
        branch: ${{ github.ref }}
